version: "3"

# ==============================================================================
# CharacterMarkdown Modular Taskfile
# ==============================================================================
# This Taskfile is organized into logical components located in taskfiles/
# Use 'task --list' to see all available tasks.
# ==============================================================================

includes:
  dev:
    taskfile: ./taskfiles/Dev.yaml
    internal: false
  build:
    taskfile: ./taskfiles/Build.yaml
    internal: false
  install:
    taskfile: ./taskfiles/Install.yaml
    internal: false
  release:
    taskfile: ./taskfiles/Release.yaml
    internal: false
  examples:
    taskfile: ./taskfiles/Examples.yaml
    internal: false

tasks:
  # ----------------------------------------------------------------------------
  # Convenience Aliases
  # ----------------------------------------------------------------------------

  default:
    desc: List all available tasks
    cmds:
      - task --list

  lint:
    desc: Alias for dev:lint
    cmds:
      - task dev:lint

  format:
    desc: Alias for dev:format
    cmds:
      - task dev:format

  test:
    desc: Alias for dev:test
    cmds:
      - task dev:test

  validate:
    desc: Alias for dev:validate
    cmds:
      - task dev:validate

  build:
    desc: Alias for build:release
    cmds:
      - task build:release

  install:
    desc: Alias for install:live
    cmds:
      - task install:live

  version:
    desc: Alias for release:version
    cmds:
      - task release:version

  # ----------------------------------------------------------------------------
  # Initialization
  # ----------------------------------------------------------------------------

  init:
    desc: Initialize development environment
    cmds:
      - task dev:install:deps
      - pre-commit install
      - task install:dev
    status:
      - test -f .git/hooks/pre-commit
