-- CharacterMarkdown - Footer Section Generator
-- Generates markdown footer section

local CM = CharacterMarkdown

-- =====================================================
-- FOOTER
-- =====================================================

local function GenerateFooter(format, currentLength)
    local markdown = ""
    
    -- Calculate character count for warnings
    local charCount = currentLength + 200  -- Approximate with footer
    
    if format == "github" then
        markdown = markdown .. "<div align=\"center\">\n\n"
        markdown = markdown .. "**Generated by Character Markdown v" .. CM.version .. "**\n\n"
        markdown = markdown .. "*Format: " .. format:upper() .. "*\n\n"
        markdown = markdown .. "</div>\n\n"
    else
        markdown = markdown .. "\n```\n"
        markdown = markdown .. string.rep("━", 80) .. "\n"
        markdown = markdown .. string.rep(" ", 20) .. "Generated by Character Markdown v" .. CM.version .. "\n"
        markdown = markdown .. string.rep(" ", 30) .. "Format: " .. format:upper() .. "\n"
        markdown = markdown .. string.rep("━", 80) .. "\n"
        markdown = markdown .. "```\n\n"
    end
    
    -- Add invisible padding to prevent clipboard truncation
    -- ESO's clipboard system sometimes truncates the last 50-100 characters
    -- This padding ensures the actual footer is preserved during copy operations
    markdown = markdown .. string.rep(" ", 150) .. "\n"
    
    return markdown
end

-- =====================================================
-- EXPORTS
-- =====================================================

CM.generators.sections.GenerateFooter = GenerateFooter

