-- CharacterMarkdown - Footer Section Generator
-- Generates markdown footer section

local CM = CharacterMarkdown

local markdown
local string_format = string.format

local function InitializeUtilities()
    if not markdown then
        markdown = CM.utils.markdown
    end
end

-- =====================================================
-- ICON LEGEND
-- =====================================================

local function GenerateLegend(format)
    if format == "discord" or format == "quick" then
        return ""
    end
    
    return string_format([[
---

## 📖 Icon Legend

<table style="width: 100%%; border-collapse: collapse;">
<tr>
<td style="vertical-align: top; padding: 0 15px; width: 50%%;">

### Section Icons
| Icon | Meaning |
|:-----|:--------|
| 📋 | Overview & Summary |
| 💰 | Currency, Resources & Inventory |
| ⚔️ | PvP & Combat |
| 🎨 | Collectibles |
| 🏆 | Achievements & Titles |
| ⚡ | Equipment Enhancement |
| 🌍 | World Progress |
| 🏰 | Guilds, Armory & Undaunted |
| 🗺️ | DLC & Chapter Access |
| 🎯 | Champion Points |
| 🎯 | Attributes & Analysis |
| 🍖 | Active Buffs |
| 📈 | Progression & Statistics |
| 🌿 | Skill Morphs |
| 📜 | Character Progress |
| 👥 | Companion |
| ⚒️ | Craft Discipline |
| 💪 | Fitness Discipline |
| ⚔️ | Warfare Discipline |

</td>
<td style="vertical-align: top; padding: 0 15px; width: 50%%;">

### Status Indicators
| Icon | Meaning |
|:-----|:--------|
| ✅ | Complete, Maxed, Good Status |
| ⚠️ | Warning, Needs Attention |
| 🔴 | Critical, High Priority |
| 🟡 | Medium Priority, Gold Quality |
| 🟢 | Low Priority, Green Quality |
| 🟣 | Purple Quality |
| 🟠 | Orange Quality |
| ⚪ | White Quality, Not Started |
| 🔄 | In Progress, Active |

### Champion Points
| Icon | Meaning |
|:-----|:--------|
| ⭐ | Slotted Slottable Star (Active) |
| ☆ | Unslotted Slottable Star (Has Points, Not Active) |
| 🔒 | Passive Skill (No Slotting Required) |

### Attributes
| Icon | Meaning |
|:-----|:--------|
| 🔵 | Magicka |
| ❤️ | Health |
| ⚡ | Stamina |

### Investment Levels
| Icon | Meaning |
|:-----|:--------|
| 🔥 | Very High (1500+ CP) |
| ⭐ | High (1200+ CP) |
| 💪 | Medium-High (800+ CP) |
| 📈 | Medium (400+ CP) |
| 🌱 | Low (<400 CP) |

</td>
</tr>
</table>

---
]], "")
end

-- =====================================================
-- FOOTER
-- =====================================================

local function GenerateFooter(format, contentLength)
    InitializeUtilities()
    
    -- Enhanced visuals are now always enabled (baseline)
    
    if format == "quick" then return "" end
    
    -- Use ESO API for timestamp (os.date() is disabled in ESO Lua)
    local timestamp = ""
    local timeSuccess, timeStamp = pcall(GetTimeStamp)
    if timeSuccess and timeStamp then
        local dateSuccess, dateString = pcall(GetDateStringFromTimestamp, timeStamp)
        if dateSuccess and dateString then
            timestamp = dateString
        else
            timestamp = "unknown time"
        end
    else
        timestamp = "unknown time"
    end
    
    local formatNumber = CM.utils and CM.utils.FormatNumber
    local safeFormatNumber = function(val)
        if formatNumber then
            return formatNumber(val)
        else
            return tostring(val)
        end
    end
    
    if format == "discord" then
        -- Classic format
        return string.format([[

---

*Generated by CharacterMarkdown (%s) on %s*  
*Total size: ~%d characters*
]], format:upper(), timestamp, contentLength or 0)
    end
    
    -- ENHANCED: Use separator and attractive footer (only if markdown utilities are available)
    if not markdown then
        -- Fallback to classic if markdown utilities not loaded
        return string.format([[
---

*Generated by CharacterMarkdown (%s) on %s*  
*Total size: ~%s characters*
]], format:upper(), timestamp, safeFormatNumber(contentLength or 0))
    end
    
    -- Create attractive footer with badges and centered layout
    local formatBadge = markdown.CreateBadge("Format", format:upper(), "blue", "flat")
    local sizeBadge = markdown.CreateBadge("Size", safeFormatNumber(contentLength or 0) .. " chars", "purple", "flat")
    
    local badgeRow = string_format("%s %s", formatBadge, sizeBadge)
    
    local footerContent = string_format([[
---

<div align="center">

%s

**⚔️ CharacterMarkdown**

<sub>Generated on %s</sub>

</div>
]], badgeRow, timestamp)
    
    return footerContent
end

-- =====================================================
-- EXPORTS
-- =====================================================

CM.generators.sections = CM.generators.sections or {}
CM.generators.sections.GenerateFooter = GenerateFooter
CM.generators.sections.GenerateLegend = GenerateLegend

CM.DebugPrint("GENERATOR", "Footer section generator loaded (enhanced visuals)")
