-- CharacterMarkdown - Footer Section Generator
-- Generates markdown footer section

local CM = CharacterMarkdown

-- =====================================================
-- FOOTER
-- =====================================================

local function GenerateFooter(format, currentLength)
    local markdown = ""
    
    -- Calculate character count for warnings
    local charCount = currentLength + 200  -- Approximate with footer
    
    if format == "github" then
        markdown = markdown .. "<div align=\"center\">\n\n"
        markdown = markdown .. "**Generated by Character Markdown (" .. format:upper() .. ")**\n\n"
        markdown = markdown .. "</div>\n\n"
    else
        markdown = markdown .. "\n```\n"
        markdown = markdown .. string.rep("━", 80) .. "\n"
        markdown = markdown .. string.rep(" ", 20) .. "Generated by Character Markdown (" .. format:upper() .. ")\n"
        markdown = markdown .. string.rep("━", 80) .. "\n"
        markdown = markdown .. "```\n\n"
    end
    
    -- Add minimal invisible padding to prevent clipboard truncation
    -- ESO's EditBox may truncate at boundaries when copying to clipboard
    -- Minimal padding (10 spaces) ensures any truncation hits padding, not content
    -- This is the smallest amount that still provides protection without visible whitespace
    -- Note: Content is already chunked at safe boundaries (~26k chars), so minimal padding is sufficient
    markdown = markdown .. string.rep(" ", 10) .. "\n"
    
    return markdown
end

-- =====================================================
-- EXPORTS
-- =====================================================

CM.generators.sections = CM.generators.sections or {}
CM.generators.sections.GenerateFooter = GenerateFooter

